### ISSUE TITLE
Safes/Registers you can rob them without items.

### ISSUE THREAD

**Issue by itscahe** [zf-labo/zf-storerobbery#2]
You can rob safes and registers without items. Tested on latest ESX Legacy.

**Comment by zf-development** [comment]
ESX or QBCore?

**Comment by itscahe** [comment]
> ESX or QBCore?

ESX

**Comment by zf-development** [comment]
Any errors?
Did you checked the fxmanifest and comment the qb-core and uncommented the esx?

**Comment by itscahe** [comment]
No errors and yeah
