### ISSUE TITLE
Switch all my things to ox_lib and esx and im still getting qb-core stuff

### ISSUE THREAD

**Issue by stxrlite** [zf-labo/zf-storerobbery#4]
![image](https://user-images.githubusercontent.com/78002427/204148903-251be674-f886-43cf-87f9-8762e9e2aa2b.png)

**Comment by zf-development** [comment]
Can you send the `shared_scripts` section of the fxmanifest please.

**Comment by zf-development** [comment]
Because it should look like this

For ESX, the shared_scripts should be this:
```lua
shared_scripts {
    'shared/*.lua',
    
    -- ### ESX ###
    '@ox_lib/init.lua',
    '@es_extended/imports.lua',
    '@es_extended/locale.lua',
    'esx_locales/*.lua',
    
    
    -- ### QB ###
    --'@qb-core/shared/locale.lua',
    --'qb_locales/*.lua',
}
```

For QBCore, the shared_scripts should be this:
```lua
shared_scripts {
    'shared/*.lua',
    
    -- ### ESX ###
    --'@ox_lib/init.lua',
    --'@es_extended/imports.lua',
    --'@es_extended/locale.lua',
    --'esx_locales/*.lua',
    
    
    -- ### QB ###
    '@qb-core/shared/locale.lua',
    'qb_locales/*.lua',
}
```

**Comment by stxrlite** [comment]
oh thanks so much

**Comment by stxrlite** [comment]
another question im using ox-lib too should i uncomment those?

**Comment by zf-development** [comment]
It's really what you want. If you want it to go out the box no more install, well go with ox_lib.
I would recommend for ESX to use ox_lib for the registers and boosthacking for the safes.

**Comment by stxrlite** [comment]
kk thank you so much
